---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  releaseName: longhorn
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
