apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - secret.yaml
  - release.yaml

configMapGenerator:
  - name: infomaniak-webhook-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
