apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infomaniak-webhook
  namespace: cert-manager
spec:
  releaseName: infomaniak-webhook
  interval: 15m
  chart:
    spec:
      chart: deploy/infomaniak-webhook
      sourceRef:
        kind: GitRepository
        name: infomaniak-webhook
        namespace: cert-manager

  valuesFrom:
    - kind: ConfigMap
      name: infomaniak-webhook-values
