apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  namespace: paperless
spec:
  description: "Postgres cluster for paperless database"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 2

  inheritedMetadata:
    labels:
      app: paperless

  storage:
    storageClass: database
    size: 5Gi

  managed:
    services:
      disabledDefaultServices:
        - r
        - ro

  affinity:
    enablePodAntiAffinity: true
