---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actual-oauth-secrets
  namespace: actual-budget
spec:
  encryptedData:
    clientId: AgButCJ4tBhHKKYnr3RjX7D1s02HPBfsgsMYjJjjAioWLrba5gcgyMA8Kk+kwNkQDLoGKiesng47gPizaTiIerP+5CbOGTxIVKPHx6nfpo/I538AuQzlujj0S2jVgmKA+Bx3RmbaYlmUXHnrfXAFO3fKBm0YLigY/rwhrJ3Pphp1+GcXLWyYB1oOniw2E8cWwmFpte5m84+MP9QGX7BQPzXv7ou5QSVr0QWFzgJaPWSFbJF7i7ZOWxeOI9QS/iczDcOZI1C/TSwkPdIW/8/LFE+cr4AHX3qY3X5kfUx581rnl9sGSXju3MI+TIGpv4SK69hFg7HXqQthKazeDddGhH2iGmUR0Z18UKT6FzymLWPYzecMOrS3bWJ0R7nELGgku6J+m98mPMbVuTlR5suFNKqG/v4wmOteJaVCLRtHawHXR4SqqYipguk9tjfnnElr702iyIzv/tKcj7p/CccC/AkEnIzxfMkDKzG4Dt1YKZt9YGoOYghfRsl9F3IIKqDf9c4tVBgrgpzlSBLPP10IVy4du6Jjo5z4e6m47DVkH8i1Nt9XcR8w+wTK43Lvzto2FObEllAHHhcx461i6I0i9Zf7Q1FNKaB7Ldl1zpFxR+Ks0fGNo2iOs9rjtES49cAM7L0RszSXXzMagxMR5LTRbuZTDXMe1YjoubdToLASW1kt5Fc3TwRX4YRFIVPweOI24tCe9Ch6j48sauNVcyXTN3YPEUWmtC8s2dqjmsgsiqSdRpwJFco=
    clientSecret: AgCFDuglVAoXoxNqsQD4wdruI/LUoeZAcZlHTkjU9ZJETm0IKPytJ3bmJBUMSR5U/5PvvKXfkF0f9GR5pAfKJxfF7wOJCMn1UvwZATH/XuLFsIJDmcu/reV3fcd4PEbXeAztRNDGy9f7/WcKDiDD3bHSDDv4rA/8hoTBLP46Nk6AMkP1HI/RbDzdiVcSau2nIDap9ykKGRr3wvFoUSb0llPIAomQYzBIuUD26xorq/QV99Vc8ImvFknhagfS9A/0LiIPfSdTDJN5OmAxQN0pMAMp2GglbLVHN2/JQ+fi00vu9x8gs929r7Mi12qbCGaPvEphOxLRo1HAxduNCaxCJguC3iMlfLqdY7cmk//+xQeNiVEW1FIqgh83bdGZfBVB57xJGeboda4CSvHjJxZncr99fjBLlViU329GWdP8vev/YHYyQLeplDlrLDyBml1XIe3+cpt2Yzh75pAf+CvQR+KARbswR+VGcRsHbrPmHDxsXuSy1utuNjR+RZJz4iCeAhJh7k1EavHmEX0oIo9SsGn3iEGzUKqyBZwyqRmWK3tvUJQLud6S1Y8/Vxz5yICYZ6VNRgcfKImHQpH9udeOebtiqiKzy2wkO/+WqbFWXo9Cv2bSJFklqZRfuEvT09djAZqZKaMVVlzYOVGELe7b4jDkMSM1E4WOcX72a8dH87TYqRxTcwpzefLtRzCzgXmwcy9GGICspWvccrwvPf/2Pisf6UH1PH3KAOVUVCPUXX0lcQ==
  template:
    metadata:
      name: actual-oauth-secrets
      namespace: actual-budget
