apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
