apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data-pvc
  namespace: pocket-id
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
