---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  encryptedData:
    ENCRYPTION_KEY: AgCBdTC9g0FpHpTxgEm9Q9YgnbIfXxLpC2t7Jdsm8AAaeivE93cbeMYmOBCEIDy/88W4sYuWes5311yBVcODSSmzpRi+x4cw40IdUs+ivm3acMI+c2H1lGVQfvsnx6DOksIrhrq4l7j5vuKkK8Jgpwr+wAPAFEa2WmpIaxdHKC2BJSOKoQcVDlCzWZixHC2uI8MfsxdSnsNrqR3Z43KfaWMdTCVHOTKDulRSMm9ci2H89qVBp7znbrwkxR3SmlZFknKxa0TkJ1LDWr0h7be3X1de73J6vfbESDycqkCnaCfEDHKti2sRQK4Vt3QpxLTNkNCPXD8nPrKETPWjbJFYKZVw80cciTUwzvPxipsk/ibQnXEZxs5ggKz72hg8gZh+UfoI0I6OVnsY6h7rlrDgnbD7vEbaYn4OJC9K0znzcfCiwC69wcqR3AefJ/iIm54Jzq9bV2MlRysQ7x+4kiEZJ1VHdDSuccLpnEoh1+ZMw5G6e9L1cBRUWxajmv5wYUXfgLYzvsFLwHUsT1almAczz+37LA5YiYhdByng8iaDIbgcyt5YUfogbGqPXJqvSw2sGUIJ1DJ3EzRzxRjRI9iuJiqc+BzryYJRVLCQmnhEUAMM0pD3WoXdo+S3Fs7glmmI5M98+hUaHb3PGaB9HmZpnjOH/E16T7MjRl0kRDEr/kRIL5cyc4gprYJUZ6CaN59UL/3y3cOKbATSrmx+5GysfS/al6HjhHsSjm6EWr/9uHD+vXvoAFwkzVOLWG68kw==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: pocket-id
