apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  releaseName: pihole
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.35.0 
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: pihole

  valuesFrom:
    - kind: ConfigMap
      name: pihole-values
