ipam:
  operator:
    clusterIPv4PodCIDRList: ["10.42.0.0/16"]
kubeProxyReplacement: true

k8sServiceHost: 10.100.30.11
k8sServicePort: 6443

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

l2announcements:
  enabled: true

gatewayAPI:
  enabled: true

# Calculated based on 30 services
# https://docs.cilium.io/en/latest/network/l2-announcements/#sizing-client-rate-limit

k8sClientRateLimit:
  qps: 15
  burst: 20
