apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets-controller
  interval: 15m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.x
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
