---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: pihole
spec:
  encryptedData:
    adminPassword: AgBBabivItKc0wd8W3kCqdqZ9rExyzpZfqqFQHKaBQRKu2R/AErGWPnTZ42cFXweccJIXhcSQfa6RsZBKQp1w3trAQZeHwGSEeOyv1i4KyU6dk06E6ugPPkb1DmdnWWRiPlPg0Gceu/WsHXK0XWF9qII9bnNz08ElTC9P4zddzi/03YTyU5dcvgV+6XKWW+YfyRVJqf/sZ6msi920ezTgN4HggUWaU1LQEhSOe4T8KNpWAe1mjcn+bb99Ex8NPjmGkufxCxyZgr4uhvJ7+Qz8swcZy2AJZxYX3byagevQaxsMlJOSdBgSD1RXF1205GBywHMixHVBAUmVLN6p26Qpkyr5FRyA4ur0j8xAWAQfaiHrrImVkA1oYzf9jr6kUtDnpKlSWvJl4PE6tHCXWmUiKmb2CU4yeyzkYNNdUv3rXHnTrUcXyy07SLmkF15Jl63ttGCFSDyR4cjpFv+1sj98RhT4XlCZsk2Wpu7iWJPLoBLZMAjoix2yVSTqqZ8swNTOgp4ky9gu/iLSIxZ+sOExHtYjSvdaf2G24HMMmwcKqSGolG94+osg6tWYQ4uG9EKCMyvWzJC2rs/M+UTSmIf3knMZdUETxHHLYa8A8qGutfoqpgK9VRohIRIbHkZl7wsjIpEa2VCuSZPuXDg8s0HlGZaqYDjIjxBjHJod03VNOZ3KGdYGFpLdwWdOtCJmOqAwgb/PSMaS5Y2E5eyEger3392pDuLwA==
  template:
    metadata:
      name: pihole-secrets
      namespace: pihole
