---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgAls0LePtpwVagoMYbNKVJo7ppSFOoPjo0TU4r7uOPwWlMT2nf25EWMUjybHmWbCcyJ1Oyolye+sBRgfh4eDN9Mex+qraq+Fg7pYxGjpdGPptTnHRposf+FItIFjNFqpJcsxw3eHSkTm/sN/qwYXI0DeUr3ihSFKYrOcxazwbMv9MqZzyO+GriNhjetKlfvDznJJKxsW1gqef+0vG1xRAXq3d8PXkDJk4wpDGoVoX6urjR0x0c/QSdYYxbIXEy1A9MuIHzMO/YEsyDlaIPIRIPZktWi9mGLCsn05+zSdEeo6Iweq0xyQofVQeajkMrpFrjrDxpjfzvg0sU6mqyTgGsmW39g4S9x/Lcry6Ts7wZcBd/bMgpfMUO/1Cow6RVi0tbo6Fovh3VOEvXYDgQLi1HdZ62/1koJAenhR7k3+Ft0ylK2rPQBPK7LdsYuUQpH9q0585A8XmgM2c7Gep6IL3YfSDTuFPxG05K8JeJBMd2ZXNKpMkC2a8aNydU1Ka2BT9IHG1bRuu4dMDwG11mAEker7iRus97n+PTZ0f83xgMT2RR/rs5xd6dkKl5www03QA+C/me3OtDEimX1rKgd5QA+FM0cpC1J/COY4x3uvDvddtmEsQmMegNhB1cE+/MKpETh1XouhEBLdb5r1xU4qMn+H1J3cXj3KcrpfsRIMz4q3Ryqp6UCk0QNAMZxK3Q5tFQ9mNQxK0y6s72Q2pE=
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
